platform:ios,'10.0'

target 'UIGracefulWriting' do
    
pod 'JSONModel'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'GPUImage'
pod 'IGListKit'
pod 'LEEAlert'
pod 'TYAttributedLabel'
pod 'SDWebImage'
pod 'SWTableViewCell'
pod 'CYLTabBarController'
pod 'FMDB'
pod 'YYKit'
pod 'MJRefresh'
pod 'MJExtension'
pod 'DZNEmptyDataSet'
pod "Texture"

pod 'SVPullToRefresh'
pod 'AFNetworking'
pod 'ComponentKit'
pod 'FlexLib'

end
